# Generated by Django 6.0.1 on 2026-02-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('product_type', models.CharField(choices=[('software', 'Software'), ('hardware', 'Hardware')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Upload software / firmware / docs', null=True, upload_to='our_products/')),
                ('external_link', models.URLField(blank=True, help_text='Optional GitHub / docs / external link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
