# Generated by Django 6.0.1 on 2026-02-10 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourproduct',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='our_products/previews/'),
        ),
        migrations.AddField(
            model_name='ourproduct',
            name='short_description',
            field=models.CharField(default=django.utils.timezone.now, help_text='One-line summary shown on cards', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ourproduct',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='our_products/files/'),
        ),
    ]
