# Generated by Django 6.0.1 on 2026-02-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_products', '0003_productcomment_productlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourproduct',
            name='short_description',
            field=models.CharField(max_length=300),
        ),
    ]
